Resources:
  WebSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: WebServerSG
      GroupDescription: Enable HTTP access on port 80
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 46.149.184.7/32
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      SecurityGroups:
        - !Ref WebSG
      InstanceType: t2.micro
      ImageId: ami-0191d47ba10441f0b
      Tags:
        - Key: Name
          Value: Custom-Apache-Web-Server
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            # Update package list and install Apache
            dnf update -y
            dnf install -y httpd

            # Start and enable Apache service
            systemctl start httpd
            systemctl enable httpd

            # Set permissions for Apache root directory
            chown -R ec2-user:ec2-user /var/www/html

            # Create a custom index.html page
            cat <<EOF > /var/www/html/index.html
            <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>Welcome to My Custom Apache Server</title>
                <style>
                    body {
                        font-family: Arial, sans-serif;
                        background-color: #f4f4f4;
                        text-align: center;
                        padding: 50px;
                    }
                    .container {
                        background: white;
                        padding: 20px;
                        border-radius: 10px;
                        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
                        display: inline-block;
                    }
                    h1 {
                        color: #333;
                    }
                    p {
                        color: #666;
                    }
                </style>
            </head>
            <body>
                <div class="container">
                    <h1>Welcome to My Custom Apache Web Server!</h1>
                    <p>Hosted on an Amazon Linux 2023 EC2 Instance.</p>
                    <p>This page was deployed automatically using AWS User Data.</p>
                </div>
            </body>
            </html>
            EOF

            # Restart Apache to apply changes
            systemctl restart httpd
  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref WebServer

